service: nest-test

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  stage: v2

functions:
  main:
    handler: dist/index.handler
    events:
      - http:
          method: GET
          path: /default/nest-serverless
