service: nest-test

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  stage: v2
  region: us-east-2
  timeout: 30
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
          - ssm:GetParameters
          - ssm:GetParameter
          - ssm:GetParametersByPath
          Resource: '*'
  layers:
    - arn:aws:lambda:us-east-2:590474943231:layer:AWS-Parameters-and-Secrets-Lambda-Extension:4
    
package:
  individually: true
  excludeDevDependencies: true
  patterns:
    - '!.github'
    - '!.vscode'
    - '!node_modules/**'
    - '!src/**'
    - '!test/**'
    - '!.env.example'
    - '!.eslintrc.js'
    - '!.gitignore'
    - '!.prettierrc'
    - '!nest-cli.json'
    - '!README.md'
    - '!sonar-project.properties'
    - '!tsconfig.*'


functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: GET
          path: /cats
          integration: lambda-proxy
          cors:
            origin: '*'
            headers:
              - Access-Control-Allow-Origin
              - Authorization
              - Content-Type
              - X-Api-Key
              - X-Amz-Date
              - X-Amz-Security-Token
              - X-Amz-User-Agent
