service: nest-test

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  stage: v2
  region: us-east-2
  timeout: 30
  layers:
    - arn:aws:lambda:us-east-2:590474943231:layer:AWS-Parameters-and-Secrets-Lambda-Extension:4
    
package:
  individually: true
  excludeDevDependencies: true
  patterns:
    - 'dist/**'
    # - '!.github'
    # - '!.vscode'
    # - '!node_modules/**'
    # - '!src/**'
    # - '!test/**'
    # - '!.env.example'
    # - '!.eslintrc.js'
    # - '!.gitignore'
    # - '!.prettierrc'
    # - '!nest-cli.json'
    # - '!README.md'
    # - '!sonar-project.properties'
    # - '!tsconfig.*'


functions:
  main:
    handler: dist/index.handler
    events:
      - http:
          method: GET
          path: /user
          integration: lambda-proxy
          cors:
            origin: '*'
            headers:
              - Access-Control-Allow-Origin
              - Authorization
              - Content-Type
              - X-Api-Key
              - X-Amz-Date
              - X-Amz-Security-Token
              - X-Amz-User-Agent
      - http:
          method: POST
          path: /token
          integration: lambda-proxy
          cors:
            origin: '*'
            headers:
              - Access-Control-Allow-Origin
              - Authorization
              - Content-Type
              - X-Api-Key
              - X-Amz-Date
              - X-Amz-Security-Token
              - X-Amz-User-Agent
      - http:
          method: POST
          path: /token/introspection
          integration: lambda-proxy
          cors:
            origin: '*'
            headers:
              - Access-Control-Allow-Origin
              - Authorization
              - Content-Type
              - X-Api-Key
              - X-Amz-Date
              - X-Amz-Security-Token
              - X-Amz-User-Agent
      - http:
          method: POST
          path: /token/revocation
          integration: lambda-proxy
          cors:
            origin: '*'
            headers:
              - Access-Control-Allow-Origin
              - Authorization
              - Content-Type
              - X-Api-Key
              - X-Amz-Date
              - X-Amz-Security-Token
              - X-Amz-User-Agent
