name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy_lambda:
    environment: TEST
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Configure ENV Variables
        run: |
          echo "${{ secrets.ENV_FILE }}" >> .env
      - name: npm install
        env: 
          CI: true
        run: |
          npm ci
      - name: deploy
        run: |
          mkdir -p layers/deps/nodejs && cp package* layers/deps/nodejs
          zip layers.zip layers/*
          npm run build
          npm run deploy
          

