name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy_lambda:
    environment: TEST
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Configure ENV Variables
        run: |
          echo "${{ secrets.ENV_FILE }}" >> .env
      - name: npm install
        env: 
          CI: true
        run: |
          npm ci
      - name: deploy
        run: |
          mkdir layers && mkdir layers/deps && mkdir layers/deps/nodejs && cp package* layers/deps/nodejs
          zip -r9 layers.zip ./layers/*
          aws lambda publish-layer-version --layer-name deps-layer --description "node deps" --zip-file fileb://layers.zip --compatible-runtimes nodejs10.x nodejs12.x nodejs14.x
          npx ncc build src/main.ts -m
          zip -j deploy.zip ./dist/* .env
          aws lambda update-function-code --function-name=nest-serverless --zip-file=fileb://deploy.zip

